# Generated by Django 4.1.2 on 2022-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to=None)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
