# Generated by Django 4.1.2 on 2022-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_student_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('date_enroll', models.DateField(auto_now=True)),
                ('date_close', models.DateField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
