# Generated by Django 4.1.2 on 2022-10-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_enrollment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_close',
            field=models.DateField(null=True),
        ),
    ]
