# Generated by Django 4.1.2 on 2022-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_alter_enrollment_date_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Cursando')], default='C', max_length=1, null=True),
        ),
    ]
