# Generated by Django 4.1.2 on 2022-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='score',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Cursando')], default='Cursando', max_length=1),
        ),
    ]
