# Generated by Django 4.1.2 on 2022-10-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_alter_enrollment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('C', 'Cursando'), ('A', 'Aprovado'), ('R', 'Reprovado')], default='C', max_length=1),
        ),
    ]
