# Generated by Django 4.1.2 on 2022-11-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0027_enrollmentfullinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentFullInfo',
        ),
    ]
